# Generated by Django 6.0.1 on 2026-06-09 09:17

from django.db import migrations, models


def set_is_spo_from_wp(apps, schema_editor):
    """Backfill: articles imported from the SPO WordPress blog are SPO news."""
    Article = apps.get_model("news", "Article")
    Article.objects.filter(wp_post_id__isnull=False).update(is_spo=True)


def unset_is_spo(apps, schema_editor):
    Article = apps.get_model("news", "Article")
    Article.objects.update(is_spo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_wp_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Новина СПО',
                'verbose_name_plural': 'Новини СПО',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
        migrations.AddField(
            model_name='article',
            name='is_spo',
            field=models.BooleanField(db_index=True, default=False, help_text='Якщо увімкнено — новина належить до розділу СПО і не показується у загальних новинах', verbose_name='Новина СПО'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['wp_post_id'], name='news_articl_wp_post_bb3209_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_spo', '-published_at'], name='news_articl_is_spo_b1b1c4_idx'),
        ),
        migrations.RunPython(set_is_spo_from_wp, unset_is_spo),
    ]
