# Generated by Django 6.0.1 on 2026-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Повне ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('workplace', models.CharField(blank=True, max_length=200, verbose_name='Місце роботи / підприємство')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Посада / професія')),
                ('message', models.TextField(blank=True, verbose_name='Додаткова інформація')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачі')),
            ],
            options={
                'verbose_name': 'Заявка на вступ',
                'verbose_name_plural': 'Заявки на вступ до профспілки',
                'ordering': ('-created_at',),
            },
        ),
    ]
