# Generated by Django 6.0.1 on 2026-06-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_join_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberorganization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='member_orgs/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='memorgpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='mem_org_pages/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pagesections/', verbose_name='Фонове зображення'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото'),
        ),
    ]
