# Generated by Django 6.0.1 on 2026-06-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_local_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoHomeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.JSONField(blank=True, default=list, verbose_name='Новини')),
                ('videos', models.JSONField(blank=True, default=list, verbose_name='Відео')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='Фотогалерея')),
                ('partners', models.JSONField(blank=True, default=list, verbose_name='Партнери')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронізовано')),
            ],
            options={
                'verbose_name': 'Кеш головної СПО',
                'verbose_name_plural': 'Кеш головної СПО',
            },
        ),
    ]
