# Generated by Django 6.0.1 on 2026-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_spo_home_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_youtube_url',
            field=models.URLField(blank=True, help_text='Посилання на конкретне відео YouTube, яке показується в блоці «Відео» на головній. Якщо порожньо — береться з останніх новин автоматично.', verbose_name='YouTube відео в hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube-канал'),
        ),
    ]
