# Generated by Django 6.0.1 on 2026-06-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hero_youtube_url'),
        ('news', '0006_spoarticle_article_is_spo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_lead_article',
            field=models.ForeignKey(blank=True, help_text='Стаття, яка показується великим блоком зліва. Якщо не вказано — береться найновіша зі «Головних новин» або перша зі стрічки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article', verbose_name='Головна стаття (ліворуч у hero)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_youtube_url',
            field=models.URLField(blank=True, help_text='Напр. https://www.youtube.com/watch?v=XXXXX — саме це відео показуватиметься у блоці «Відео». Якщо порожньо — береться з останніх новин автоматично.', verbose_name='Відео (hero) — YouTube посилання'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube-канал (посилання в футері)'),
        ),
    ]
