# Generated by Django 6.0.1 on 2026-06-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hero_lead_article'),
        ('news', '0006_spoarticle_article_is_spo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_slide_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article', verbose_name='Hero: слайд 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_slide_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article', verbose_name='Hero: слайд 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_slide_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article', verbose_name='Hero: слайд 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_slide_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article', verbose_name='Hero: слайд 4'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_lead_article',
            field=models.ForeignKey(blank=True, help_text='Якщо не вказано — береться найновіша з категорії «Головна новина».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article', verbose_name='Hero: головна стаття (великий блок зліва)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_youtube_url',
            field=models.URLField(blank=True, help_text='Напр. https://www.youtube.com/watch?v=XXXXX. Якщо порожньо — береться з останніх новин автоматично.', verbose_name='Hero: відео — YouTube посилання'),
        ),
    ]
