# Generated by Django 6.0.1 on 2026-07-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hero_slides'),
        ('news', '0006_spoarticle_article_is_spo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='detail_article',
            field=models.ForeignKey(blank=True, help_text='Якщо вказано — картка стане клікабельною і веде на цю статтю.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article', verbose_name='Стаття з докладною біографією'),
        ),
    ]
