# Generated by Django 6.0.1 on 2026-06-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/photos/', verbose_name='Фото'),
        ),
    ]
