# Generated by Django 6.0.1 on 2026-06-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_local_image_fields'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoekspSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Експозиція 2024', help_text='Невеликий рядок над заголовком, напр. «Експозиція 2024»', max_length=100, verbose_name='Підзаголовок банера')),
                ('banner_title', models.CharField(default='Фотовиставка', max_length=255, verbose_name='Заголовок банера')),
                ('banner_subtitle', models.TextField(blank=True, default='Федерація профспілок України — діяльність на захист незалежності країни та людини праці в умовах війни', verbose_name='Опис під банером')),
            ],
            options={
                'verbose_name': 'Налаштування фотовиставки',
                'verbose_name_plural': 'Налаштування фотовиставки',
            },
        ),
        migrations.CreateModel(
            name='FotoekspAlbum',
            fields=[
            ],
            options={
                'verbose_name': 'Альбом виставки',
                'verbose_name_plural': 'Альбоми фотовиставки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
        migrations.CreateModel(
            name='FotoekspPage',
            fields=[
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Фотовиставка — головна',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.staticpage',),
        ),
    ]
