# Generated by Django 6.0.1 on 2026-06-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_fotoeksp_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoeksppage',
            options={'verbose_name': 'Фотовиставка', 'verbose_name_plural': 'Фотовиставка'},
        ),
    ]
