# Generated by Django 6.0.1 on 2026-06-08 08:00

import django.db.models.deletion
from django.db import migrations, models


def import_fotoeksp_entries(apps, schema_editor):
    StaticPage = apps.get_model("pages", "StaticPage")
    FotoekspEntry = apps.get_model("pages", "FotoekspEntry")
    FotoekspSettings = apps.get_model("pages", "FotoekspSettings")
    Article = apps.get_model("news", "Article")

    if FotoekspEntry.objects.exists():
        return

    page = StaticPage.objects.filter(url_path="/fotoekspozytsiya").first()
    if not page or not page.body:
        return

    from apps.pages.fotoekspozytsiya import import_fotoeksp_from_html

    data = import_fotoeksp_from_html(page.body)
    settings, _ = FotoekspSettings.objects.get_or_create(pk=1)
    for field, value in data["settings"].items():
        if value:
            setattr(settings, field, value)
    settings.save()

    for item in data["entries"]:
        article = None
        joomla_id = item.get("joomla_id")
        if joomla_id:
            article = Article.objects.filter(joomla_id=joomla_id).first()
        FotoekspEntry.objects.create(
            page=page,
            section=item["section"],
            order=item["order"],
            title=item["title"],
            article=article,
            is_published=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_local_image_fields'),
        ('pages', '0003_fotoeksp_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoekspsettings',
            name='galuz_date_note',
            field=models.CharField(blank=True, default='(станом на березень 2024 р.)', max_length=255, verbose_name='Дата для галузевих'),
        ),
        migrations.AddField(
            model_name='fotoekspsettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='fotoeksp/', verbose_name='Зображення над списками'),
        ),
        migrations.AddField(
            model_name='fotoekspsettings',
            name='hero_image_local',
            field=models.CharField(blank=True, help_text='Шлях у media/joomla_images/, напр. images/2024/March/foo.jpg', max_length=500, verbose_name='Локальне зображення'),
        ),
        migrations.AddField(
            model_name='fotoekspsettings',
            name='notice_text',
            field=models.CharField(blank=True, default='(УВАГА!!! Експозиція поповнюється)', help_text='Червоний рядок під заголовком на сторінці', max_length=255, verbose_name='Попередження'),
        ),
        migrations.AddField(
            model_name='fotoekspsettings',
            name='teritorial_date_note',
            field=models.CharField(blank=True, default='(станом на березень 2024 р.)', max_length=255, verbose_name='Дата для територіальних'),
        ),
        migrations.CreateModel(
            name='FotoekspEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('teritorial', "Територіальні об'єднання"), ('galuz', 'Галузеві профспілки')], max_length=20, verbose_name='Розділ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('title', models.CharField(max_length=500, verbose_name='Назва організації')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показувати')),
                ('article', models.ForeignKey(blank=True, help_text='Якщо обрано — назва стає посиланням на альбом з фото', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotoeksp_entries', to='news.article', verbose_name='Альбом')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotoeksp_entries', to='pages.staticpage', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Рядок списку',
                'verbose_name_plural': 'Рядки списку',
                'ordering': ('section', 'order', 'pk'),
                'indexes': [models.Index(fields=['page', 'section', 'order'], name='pages_fotoe_page_id_8e9df3_idx')],
            },
        ),
        migrations.RunPython(import_fotoeksp_entries, migrations.RunPython.noop),
    ]
