# Generated by Django 6.0.1 on 2026-06-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_fotoeksp_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoekspGaluzEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Галузева профспілка',
                'verbose_name_plural': 'Галузеві профспілки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.fotoekspentry',),
        ),
        migrations.CreateModel(
            name='FotoekspTerritorialEntry',
            fields=[
            ],
            options={
                'verbose_name': "Територіальне об'єднання",
                'verbose_name_plural': "Територіальні об'єднання",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.fotoekspentry',),
        ),
    ]
