# Generated by Django 6.0.1 on 2026-06-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_fotoeksp_entry_proxies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoekspalbum',
            options={'verbose_name': 'Сторінка з фото', 'verbose_name_plural': 'Сторінки з фото'},
        ),
    ]
